apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porsev-rb
subjects:
- kind: User
  name: porsev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: porsev-role
  apiGroup: rbac.authorization.k8s.io


